//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4927
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaNGOS_GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class hcStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hcStringResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaNGOS_GUI.Resources.hcStringResources", typeof(hcStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a Message to Broadcast..
        /// </summary>
        internal static string broadcastMessage_EnterMessage {
            get {
                return ResourceManager.GetString("broadcastMessage_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This account already exists..
        /// </summary>
        internal static string createAccount_AccountExists {
            get {
                return ResourceManager.GetString("createAccount_AccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter an account name to continue..
        /// </summary>
        internal static string createAccount_EnterAccountName {
            get {
                return ResourceManager.GetString("createAccount_EnterAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a password to continue..
        /// </summary>
        internal static string createAccount_EnterPassword {
            get {
                return ResourceManager.GetString("createAccount_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no account by that name in the database..
        /// </summary>
        internal static string deleteAccount_AccountDoesntExist {
            get {
                return ResourceManager.GetString("deleteAccount_AccountDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you wish to delete this account?.
        /// </summary>
        internal static string deleteAccount_ConfirmDelete {
            get {
                return ResourceManager.GetString("deleteAccount_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Delete.
        /// </summary>
        internal static string deleteAccount_ConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("deleteAccount_ConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter an account to delete..
        /// </summary>
        internal static string deleteAccount_EnterAccount {
            get {
                return ResourceManager.GetString("deleteAccount_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured while trying to complete this action..
        /// </summary>
        internal static string Global_CommandError {
            get {
                return ResourceManager.GetString("Global_CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The following command was completed successfully: \n{0}.
        /// </summary>
        internal static string Global_CommandSuccesful {
            get {
                return ResourceManager.GetString("Global_CommandSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have not saved any config values. Default values loaded..
        /// </summary>
        internal static string Global_DataAccess_Config_NotSavedAnyConfigValues {
            get {
                return ResourceManager.GetString("Global_DataAccess_Config_NotSavedAnyConfigValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bak files (*.bak)|*.bak|All files (*.*)|*.*.
        /// </summary>
        internal static string Global_DumpFileDialogFilter {
            get {
                return ResourceManager.GetString("Global_DumpFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured while connecting to the database. Check your configuration..
        /// </summary>
        internal static string Global_ErrorConnectingDB {
            get {
                return ResourceManager.GetString("Global_ErrorConnectingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database problem.
        /// </summary>
        internal static string Global_ErrorConnectingDBShort {
            get {
                return ResourceManager.GetString("Global_ErrorConnectingDBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no character by that name in the database..
        /// </summary>
        internal static string kickCharacter_CharacterDoesntExist {
            get {
                return ResourceManager.GetString("kickCharacter_CharacterDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a charcter to kick from the server..
        /// </summary>
        internal static string kickCharacter_EnterCharacter {
            get {
                return ResourceManager.GetString("kickCharacter_EnterCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no account by that name in the database..
        /// </summary>
        internal static string loadDump_AccountDoesntExist {
            get {
                return ResourceManager.GetString("loadDump_AccountDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a file name to continue..
        /// </summary>
        internal static string loadDump_EnterFileName {
            get {
                return ResourceManager.GetString("loadDump_EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a player name or guid to continue..
        /// </summary>
        internal static string loadDump_EnterNameOrGuid {
            get {
                return ResourceManager.GetString("loadDump_EnterNameOrGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU: (Offline).
        /// </summary>
        internal static string ManguiMain_CpuOffline {
            get {
                return ResourceManager.GetString("ManguiMain_CpuOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Days:.
        /// </summary>
        internal static string ManguiMain_Days {
            get {
                return ResourceManager.GetString("ManguiMain_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Couldn&apos;t find mangos.conf file check your GUI config..
        /// </summary>
        internal static string ManguiMain_ErrorMangosConf {
            get {
                return ResourceManager.GetString("ManguiMain_ErrorMangosConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hours:.
        /// </summary>
        internal static string ManguiMain_Hours {
            get {
                return ResourceManager.GetString("ManguiMain_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mangos server is not running. Please start mangos first..
        /// </summary>
        internal static string ManguiMain_MangosNotRunning {
            get {
                return ResourceManager.GetString("ManguiMain_MangosNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mangos is already running..
        /// </summary>
        internal static string ManguiMain_MangosRunning {
            get {
                return ResourceManager.GetString("ManguiMain_MangosRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to start mangos server please check your GUI configuration..
        /// </summary>
        internal static string ManguiMain_MangosStartError {
            get {
                return ResourceManager.GetString("ManguiMain_MangosStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error Starting Mangos.
        /// </summary>
        internal static string ManguiMain_MangosStartErrorCaption {
            get {
                return ResourceManager.GetString("ManguiMain_MangosStartErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online Now: .
        /// </summary>
        internal static string ManguiMain_Online {
            get {
                return ResourceManager.GetString("ManguiMain_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Realm server is not running. Please start realm first..
        /// </summary>
        internal static string ManguiMain_RealmNotRunning {
            get {
                return ResourceManager.GetString("ManguiMain_RealmNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Realm is already running..
        /// </summary>
        internal static string ManguiMain_RealmRunning {
            get {
                return ResourceManager.GetString("ManguiMain_RealmRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to start realm server please check your GUI configuration..
        /// </summary>
        internal static string ManguiMain_RealmStartError {
            get {
                return ResourceManager.GetString("ManguiMain_RealmStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error Starting Realm.
        /// </summary>
        internal static string ManguiMain_RealmStartErrorCaption {
            get {
                return ResourceManager.GetString("ManguiMain_RealmStartErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Servers not shutdown properly. May need manual shutdown..
        /// </summary>
        internal static string ManguiMain_ServerShutdownError {
            get {
                return ResourceManager.GetString("ManguiMain_ServerShutdownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shutdown Error.
        /// </summary>
        internal static string ManguiMain_ServerShutdownErrorCaption {
            get {
                return ResourceManager.GetString("ManguiMain_ServerShutdownErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  -- Version: .
        /// </summary>
        internal static string ManguiMain_Version {
            get {
                return ResourceManager.GetString("ManguiMain_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a new player limit..
        /// </summary>
        internal static string playerLimit_EnterLimit {
            get {
                return ResourceManager.GetString("playerLimit_EnterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a character name..
        /// </summary>
        internal static string sendMeassage_EnterCharacter {
            get {
                return ResourceManager.GetString("sendMeassage_EnterCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This character does not exist..
        /// </summary>
        internal static string sendMessage_CharacterDoesntExist {
            get {
                return ResourceManager.GetString("sendMessage_CharacterDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Account:.
        /// </summary>
        internal static string serverBans_CaseAccount {
            get {
                return ResourceManager.GetString("serverBans_CaseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Character:.
        /// </summary>
        internal static string serverBans_CaseCharacter {
            get {
                return ResourceManager.GetString("serverBans_CaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter IP:.
        /// </summary>
        internal static string serverBans_CaseIP {
            get {
                return ResourceManager.GetString("serverBans_CaseIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose type of ban..
        /// </summary>
        internal static string serverBans_ChooseBanType {
            get {
                return ResourceManager.GetString("serverBans_ChooseBanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose ban or unban first..
        /// </summary>
        internal static string serverBans_ChooseBanUnban {
            get {
                return ResourceManager.GetString("serverBans_ChooseBanUnban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter an account/character/ip depending on type of ban..
        /// </summary>
        internal static string serverBans_EnterAccountCharIP {
            get {
                return ResourceManager.GetString("serverBans_EnterAccountCharIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter reason for ban..
        /// </summary>
        internal static string serverBans_EnterBanReason {
            get {
                return ResourceManager.GetString("serverBans_EnterBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter delay time in seconds..
        /// </summary>
        internal static string serverShutdown_EnterDelayTime {
            get {
                return ResourceManager.GetString("serverShutdown_EnterDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This account does not exist..
        /// </summary>
        internal static string setBC_AccountUnknown {
            get {
                return ResourceManager.GetString("setBC_AccountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose Activate/Deactivate BC..
        /// </summary>
        internal static string setBC_ChooseAction {
            get {
                return ResourceManager.GetString("setBC_ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter an account to modify..
        /// </summary>
        internal static string setBC_EnterAccount {
            get {
                return ResourceManager.GetString("setBC_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Burning Crusade.
        /// </summary>
        internal static string setexp_bc {
            get {
                return ResourceManager.GetString("setexp_bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Classic.
        /// </summary>
        internal static string setexp_classic {
            get {
                return ResourceManager.GetString("setexp_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrath of The Lich King.
        /// </summary>
        internal static string setexp_wotlk {
            get {
                return ResourceManager.GetString("setexp_wotlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This account does not exist..
        /// </summary>
        internal static string setGM_AccountUnknown {
            get {
                return ResourceManager.GetString("setGM_AccountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose a GM level..
        /// </summary>
        internal static string setGM_ChooseGMLevel {
            get {
                return ResourceManager.GetString("setGM_ChooseGMLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter an account to modify..
        /// </summary>
        internal static string setGM_EnterAccount {
            get {
                return ResourceManager.GetString("setGM_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a new MOTD..
        /// </summary>
        internal static string SetMOTD_EnterMOTD {
            get {
                return ResourceManager.GetString("SetMOTD_EnterMOTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords do not match or have not been entered..
        /// </summary>
        internal static string setPassword_PasswordNoMatch {
            get {
                return ResourceManager.GetString("setPassword_PasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no character by the name &quot;{0}&quot; in the database..
        /// </summary>
        internal static string teleChar_BadCharacterName {
            get {
                return ResourceManager.GetString("teleChar_BadCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a character to teleport..
        /// </summary>
        internal static string teleChar_PleaseEnterCharacterToTeleport {
            get {
                return ResourceManager.GetString("teleChar_PleaseEnterCharacterToTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a file name to continue..
        /// </summary>
        internal static string writeDump_EnterFileName {
            get {
                return ResourceManager.GetString("writeDump_EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a player name or guid to continue..
        /// </summary>
        internal static string writeDump_EnterPlayerName {
            get {
                return ResourceManager.GetString("writeDump_EnterPlayerName", resourceCulture);
            }
        }
    }
}
